#!/bin/sh
#create symlink
libfile="/usr/lib/libxlive.so.1.0.0"
if [ -e /usr/lib/libxlive.so ]; then
	sudo sh -c "rm /usr/lib/libxlive.so"
fi
if [ -e /usr/lib/libxlive.so.1 ]; then
	sudo sh -c "rm /usr/lib/libxlive.so.1"
fi
if [ -e /usr/lib/libxlive.so.1.0 ]; then
	sudo sh -c "rm /usr/lib/libxlive.so.1.0"
fi
sudo sh -c "ls $libfile | xargs -i ln -s $libfile /usr/lib/libxlive.so"
sudo sh -c "ls $libfile | xargs -i ln -s $libfile /usr/lib/libxlive.so.1"
sudo sh -c "ls $libfile | xargs -i ln -s $libfile /usr/lib/libxlive.so.1.0"

